# Generated by Django 4.1.3 on 2023-01-11 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField()),
                ('first_ques', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('second_ques', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('third_ques', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fourth_ques', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fifth_ques', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
