# Generated by Django 5.0.1 on 2024-04-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=500)),
                ('specializatin', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('fees', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userresponse',
            options={'get_latest_by': 'date_time'},
        ),
    ]
